// apps/angular-wallet/src/app/components/wallet-identities/wallet-identities.component.ts
import { Component, OnInit } from '@angular/core';
import { WalletService } from '../../services/wallet.service';
import Wallet, {
  IdentityInstance,
  IdentityUpdatedEvent,
} from '@arianee/wallet';
import { BrandIdentityWithOwned, ChainType } from '@arianee/common-types';

@Component({
  selector: 'app-wallet-identities',
  templateUrl: './wallet-identities.component.html',
  styleUrls: ['./wallet-identities.component.scss'],
})
export class WalletIdentities implements OnInit {
  public identities: IdentityInstance<BrandIdentityWithOwned>[] = [];
  public loading = false;

  public eventsLog = '';

  private wallet?: Wallet<ChainType>;

  constructor(public walletService: WalletService) {}

  ngOnInit(): void {
    this.walletService.wallet.subscribe(async (wallet) => {
      this.loading = true;

      this.wallet?.identity.updated.removeAllListeners();

      this.eventsLog = '';

      this.wallet = wallet;

      this.wallet.identity.updated.addListener(this.identityUpdated.bind(this));

      this.identities = await wallet.identity.getOwnedSmartAssetsIdentities();

      this.loading = false;
    });
  }

  public identityUpdated(event: IdentityUpdatedEvent) {
    this.eventsLog += `Identity ${event.issuer} updated on ${event.protocol.name}\n`;
  }

  public stringify(obj: any) {
    return JSON.stringify(obj, null, 2);
  }
}

<div>
  <h2>Identities</h2>
  <div *ngIf="loading">loading..</div>
  <div *ngIf="!loading">
    <div>
      <h4>
        Events (listening
        <div class="listening"></div>
        )
      </h4>

      <textarea readonly>{{ eventsLog }}</textarea>
    </div>
    <div *ngFor="let identity of identities" class="identity">
      <div><b>Issuer:</b> {{ identity.data.address }}</div>
      <div><b>Name:</b> {{ identity.data.content.name }}</div>
      <div><b>Owned NFTs:</b> {{ identity.data.ownedCount }}</div>
      <div><b>Protocol:</b> {{ stringify(identity.data.protocol) }}</div>
      <div>
        <b>Content:</b><br /><textarea readonly>
        {{ stringify(identity.data.content) }}
      </textarea
        >
      </div>
    </div>
  </div>
</div>

// apps/arianee-react-wallet/src/app/components/walletIdentities.tsx
import Wallet, {
  IdentityInstance,
  IdentityUpdatedEvent,
} from '@arianee/wallet';
import { useEffect, useState } from 'react';
import { BrandIdentityWithOwned, ChainType } from '@arianee/common-types';
import { getTime } from '../utils/misc';

export interface WalletIdentitiesProps {
  wallet: Wallet<ChainType>;
}

export default function WalletIdentities({ wallet }: WalletIdentitiesProps) {
  const [identities, setIdentities] = useState<
    IdentityInstance<BrandIdentityWithOwned>[]
  >([]);
  const [loading, setLoading] = useState<boolean>(false);

  const [eventsLog, setEventsLog] = useState<string>('');

  const pushToEventsLog = (message: string) => {
    setEventsLog((oldEventsLog) => message + '\n' + oldEventsLog);
  };

  const identityUpdated = (event: IdentityUpdatedEvent) => {
    pushToEventsLog(
      `[${getTime()}] Identity (${event.issuer}) updated on ${
        event.protocol.name
      }`
    );
  };

  useEffect(() => {
    setLoading(true);
    setEventsLog('');

    wallet.identity.updated.addListener(identityUpdated);

    wallet.identity.getOwnedSmartAssetsIdentities().then((identities) => {
      setIdentities(identities);
      setLoading(false);
    });

    return () => {
      wallet.identity.updated.removeAllListeners();
    };
  }, [wallet]);

  return (
    <div id="identities">
      <h3>Identities</h3>
      {loading ? (
        <div>Loading...</div>
      ) : (
        <>
          <div
            style={{
              margin: '8px',
            }}
          >
            <h4>Events log</h4>
            <textarea
              spellCheck={false}
              style={{ width: '500px', height: '100px' }}
              readOnly={true}
              value={eventsLog}
            ></textarea>
          </div>
          {identities.map((identity, index) => {
            const { data } = identity;
            const issuer = data.address;

            return (
              <div
                id={'identity-' + issuer.toLowerCase()}
                key={issuer}
                style={{
                  background: index % 2 === 0 ? '#d2baff' : '#ede3ff',
                  padding: '16px',
                  margin: '8px',
                  borderRadius: '8px',
                }}
              >
                <div>
                  <b>Issuer:</b> {issuer}
                </div>
                <div>
                  <b>Name:</b> {data.content.name}
                </div>
                <div>
                  <b>Owned NFTs:</b> {data.ownedCount}
                </div>
                <div>
                  <b>Protocol:</b> {JSON.stringify(data.protocol, undefined, 2)}
                </div>
                <div>
                  <b>Content:</b>
                  <br />
                  <textarea
                    spellCheck={false}
                    style={{ width: '300px', height: '50px' }}
                    value={JSON.stringify(data.content, undefined, 4)}
                    readOnly={true}
                  ></textarea>
                </div>
              </div>
            );
          })}
        </>
      )}
    </div>
  );
}
